### ISSUE TITLE
libgojni.so will not run on Android 5.0

### ISSUE THREAD

**Issue by adrnsoh** [getlantern/flashlight-build#188]
07-17 16:36:37.136: W/linker(7145): libgojni.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

Firetweet won't run on Android 5.x either.

**Comment by adrnsoh** [comment]
https://github.com/golang/go/issues/9210

**Comment by uaalto** [comment]
Will handle it here: https://github.com/getlantern/firetweet/issues/142
